spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}

server:
  port: 8080
